### ISSUE TITLE
Как с safeStorage взаимодействовать?

### ISSUE THREAD

**Issue by ProgrammingLife** [yandex-games-plugins/defold#1]

**Comment by koteelok** [comment]
C SafeStorage взаимодействовать не нужно, [при инициализации объект localStorage заменяется на safeStorage](https://github.com/yandex-games-plugins/defold/blob/f13c6343b79b8ffa18df20ef7865e1e5ed628b0c/ysdk/manifests/web/engine_template.html#L11-L15).
