### ISSUE TITLE
Крах игры при вызове функции ysdk.player.get_stats без параметра keys

### ISSUE THREAD

**Issue by Fossean1** [yandex-games-plugins/defold#2]
### Описание проблемы
При вызове функции ysdk.player.get_stats() без списка ключей, происходит крах игры.
При передаче пустой таблицы ysdk.player.get_stats(callback, {}) проблема исчезает.

### Аварийный дамп
`0 0x7FF732C77E20 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
 1 0x7FF73302A344 raise /tmp/job2606640729982794335/minkernel/crts/ucrt/src/appcrt/misc/signal.cpp:547
 2 0x7FF73301AA3C abort /tmp/job2606640729982794335/minkernel/crts/ucrt/src/appcrt/startup/abort.cpp:71
 3 0x7FF733019D20 common_assert_to_stderr<wchar_t> /tmp/job2606640729982794335/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:186
 4 0x7FF733019838 _wassert /tmp/job2606640729982794335/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:443
 5 0x7FF732BF26F0 dmYandex::LuaTableToJSON /tmp/job2606640729982794335/upload/ysdk/src/utils.cpp:261
 6 0x7FF732BF1C60 CPP_GetPlayerStats /tmp/job2606640729982794335/upload/ysdk/src/ysdk.cpp:456
 7 0x7FF732BF4B9E lj_BC_FUNCC <unknown>:0
 8 0x7FF732C6F3B0 lua_pcall <unknown>:0
 9 0x7FF732CA1000 dmScript::PCallInternal D:\a\defold\defold\engine\script\src\script.cpp:1386
10 0x7FF732D04C40 dmGameObject::RunScript D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:142
11 0x7FF732D034E0 dmGameObject::CompScriptInit D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:183
12 0x7FF732CD6B30 dmGameObject::InitComponents D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:1696
13 0x7FF732CD33B0 dmGameObject::InitCollection D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:1765
14 0x7FF732D41EA0 dmEngine::Init D:\a\defold\defold\engine\engine\src\engine.cpp:1311
15 0x7FF732D40DE0 dmEngineCreate D:\a\defold\defold\engine\engine\src\engine.cpp:2120
16 0x7FF732D46920 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:68
17 0x7FF732C65B50 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148
18 0x7FF732FD3C14 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
19 0x7FFB04B053D0 BaseThreadInitThunk <unknown>:0
20 0x7FFB056C4830 RtlUserThreadStart <unknown>:0`

**Comment by koteelok** [comment]
Решено в версии 1.2.0
