### ISSUE TITLE
Яндекс плагин не работает на последней стабильной версии Дефолда: 1.6.4 на iOS 17.3, 17.4

### ISSUE THREAD

**Issue by ProgrammingLife** [yandex-games-plugins/defold#3]
Протестированы версии Дефолда: 1.6.4 stable, 1.7.0 beta.

Шаги для воспроизведения:

1. Пустой проект с картинкой по центру
2. Добавляем яндекс плагин
3. HTML5 билд в Дефолд 1.6.4 (стабильная), либо 1.7.0beta
4. Закинуть в черновик
5. Открываем - видим только HTML лого Дефолда и при этом не грузится наша сцена.
6. Убираем Яндекс-плагин из проекта, перезапускаем Дефолд (чтобы кэш очистился), закидываем в черновик, запускаем - всё работает, если без плагина.

Предыдущая версия плагина: 1.0.1 - также перестала работать в свежих iOS. Возможно, в проектах, которые сбилжены в Дефолд 1.6.4.

Кто-то может подтвердить или опровергнуть?

@koteelok - Не замечали ли вы каких-нибудь проблем в последних версиях Дефолда?

**Comment by koteelok** [comment]
Закрываю, Яндекс решил проблему по их словам.
